export {default as DiamondBD} from './diamond-background.png'
export {default as SiteLogo} from './logo.png'
export {default as HeroImage} from './hero-image.png'
export {default as P1} from './p1.png'
export {default as P2} from './p2.png'
export {default as P3} from './p3.png'
export {default as P4} from './p4.png'
export {default as P5} from './p5.png'